# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: common.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import code_pb2 as code__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='common.proto',
  package='common',
  syntax='proto3',
  serialized_options=b'Z\021app/protocol/grpc',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0c\x63ommon.proto\x12\x06\x63ommon\x1a\ncode.proto\"\'\n\nBaseResult\x12\x0c\n\x04\x63ode\x18\x01 \x01(\x05\x12\x0b\n\x03msg\x18\x02 \x01(\t\"\x15\n\x04Page\x12\r\n\x05total\x18\x01 \x01(\x03\".\n\x05\x45mpty\x12\x18\n\x04\x63ode\x18\x01 \x01(\x0e\x32\n.code.Code\x12\x0b\n\x03msg\x18\x02 \x01(\t\"\x9c\x02\n\tQueryInfo\x12\x0e\n\x06\x66ields\x18\x01 \x03(\t\x12+\n\x05where\x18\x02 \x03(\x0b\x32\x1c.common.QueryInfo.WhereEntry\x12\x0c\n\x04skip\x18\x03 \x01(\x03\x12\r\n\x05limit\x18\x04 \x01(\x03\x12!\n\x08order_by\x18\x05 \x03(\x0b\x32\x0f.common.OrderBy\x12\x13\n\x0boperator_id\x18\x06 \x01(\t\x12\x15\n\roperator_name\x18\x07 \x01(\t\x12 \n\x07options\x18\x08 \x03(\x0b\x32\x0f.common.Options\x1a\x44\n\nWhereEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12%\n\x05value\x18\x02 \x01(\x0b\x32\x16.common.WhereOperation:\x02\x38\x01\"6\n\x0eWhereOperation\x12$\n\toperation\x18\x01 \x03(\x0b\x32\x11.common.Operation\"<\n\tOperation\x12\x12\n\nvalue_type\x18\x01 \x01(\t\x12\x0b\n\x03opt\x18\x02 \x01(\t\x12\x0e\n\x06values\x18\x03 \x03(\t\"&\n\x07OrderBy\x12\r\n\x05\x66ield\x18\x01 \x01(\t\x12\x0c\n\x04sort\x18\x02 \x01(\t\"n\n\x07Options\x12\x31\n\toperation\x18\x01 \x03(\x0b\x32\x1e.common.Options.OperationEntry\x1a\x30\n\x0eOperationEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\x42\x13Z\x11\x61pp/protocol/grpcb\x06proto3'
  ,
  dependencies=[code__pb2.DESCRIPTOR,])




_BASERESULT = _descriptor.Descriptor(
  name='BaseResult',
  full_name='common.BaseResult',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='code', full_name='common.BaseResult.code', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='msg', full_name='common.BaseResult.msg', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=36,
  serialized_end=75,
)


_PAGE = _descriptor.Descriptor(
  name='Page',
  full_name='common.Page',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='total', full_name='common.Page.total', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=77,
  serialized_end=98,
)


_EMPTY = _descriptor.Descriptor(
  name='Empty',
  full_name='common.Empty',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='code', full_name='common.Empty.code', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='msg', full_name='common.Empty.msg', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=100,
  serialized_end=146,
)


_QUERYINFO_WHEREENTRY = _descriptor.Descriptor(
  name='WhereEntry',
  full_name='common.QueryInfo.WhereEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='common.QueryInfo.WhereEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='value', full_name='common.QueryInfo.WhereEntry.value', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=b'8\001',
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=365,
  serialized_end=433,
)

_QUERYINFO = _descriptor.Descriptor(
  name='QueryInfo',
  full_name='common.QueryInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='fields', full_name='common.QueryInfo.fields', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='where', full_name='common.QueryInfo.where', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='skip', full_name='common.QueryInfo.skip', index=2,
      number=3, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='limit', full_name='common.QueryInfo.limit', index=3,
      number=4, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='order_by', full_name='common.QueryInfo.order_by', index=4,
      number=5, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='operator_id', full_name='common.QueryInfo.operator_id', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='operator_name', full_name='common.QueryInfo.operator_name', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='options', full_name='common.QueryInfo.options', index=7,
      number=8, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_QUERYINFO_WHEREENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=149,
  serialized_end=433,
)


_WHEREOPERATION = _descriptor.Descriptor(
  name='WhereOperation',
  full_name='common.WhereOperation',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='operation', full_name='common.WhereOperation.operation', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=435,
  serialized_end=489,
)


_OPERATION = _descriptor.Descriptor(
  name='Operation',
  full_name='common.Operation',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='value_type', full_name='common.Operation.value_type', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='opt', full_name='common.Operation.opt', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='values', full_name='common.Operation.values', index=2,
      number=3, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=491,
  serialized_end=551,
)


_ORDERBY = _descriptor.Descriptor(
  name='OrderBy',
  full_name='common.OrderBy',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='field', full_name='common.OrderBy.field', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='sort', full_name='common.OrderBy.sort', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=553,
  serialized_end=591,
)


_OPTIONS_OPERATIONENTRY = _descriptor.Descriptor(
  name='OperationEntry',
  full_name='common.Options.OperationEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='common.Options.OperationEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='value', full_name='common.Options.OperationEntry.value', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=b'8\001',
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=655,
  serialized_end=703,
)

_OPTIONS = _descriptor.Descriptor(
  name='Options',
  full_name='common.Options',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='operation', full_name='common.Options.operation', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_OPTIONS_OPERATIONENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=593,
  serialized_end=703,
)

_EMPTY.fields_by_name['code'].enum_type = code__pb2._CODE
_QUERYINFO_WHEREENTRY.fields_by_name['value'].message_type = _WHEREOPERATION
_QUERYINFO_WHEREENTRY.containing_type = _QUERYINFO
_QUERYINFO.fields_by_name['where'].message_type = _QUERYINFO_WHEREENTRY
_QUERYINFO.fields_by_name['order_by'].message_type = _ORDERBY
_QUERYINFO.fields_by_name['options'].message_type = _OPTIONS
_WHEREOPERATION.fields_by_name['operation'].message_type = _OPERATION
_OPTIONS_OPERATIONENTRY.containing_type = _OPTIONS
_OPTIONS.fields_by_name['operation'].message_type = _OPTIONS_OPERATIONENTRY
DESCRIPTOR.message_types_by_name['BaseResult'] = _BASERESULT
DESCRIPTOR.message_types_by_name['Page'] = _PAGE
DESCRIPTOR.message_types_by_name['Empty'] = _EMPTY
DESCRIPTOR.message_types_by_name['QueryInfo'] = _QUERYINFO
DESCRIPTOR.message_types_by_name['WhereOperation'] = _WHEREOPERATION
DESCRIPTOR.message_types_by_name['Operation'] = _OPERATION
DESCRIPTOR.message_types_by_name['OrderBy'] = _ORDERBY
DESCRIPTOR.message_types_by_name['Options'] = _OPTIONS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

BaseResult = _reflection.GeneratedProtocolMessageType('BaseResult', (_message.Message,), {
  'DESCRIPTOR' : _BASERESULT,
  '__module__' : 'common_pb2'
  # @@protoc_insertion_point(class_scope:common.BaseResult)
  })
_sym_db.RegisterMessage(BaseResult)

Page = _reflection.GeneratedProtocolMessageType('Page', (_message.Message,), {
  'DESCRIPTOR' : _PAGE,
  '__module__' : 'common_pb2'
  # @@protoc_insertion_point(class_scope:common.Page)
  })
_sym_db.RegisterMessage(Page)

Empty = _reflection.GeneratedProtocolMessageType('Empty', (_message.Message,), {
  'DESCRIPTOR' : _EMPTY,
  '__module__' : 'common_pb2'
  # @@protoc_insertion_point(class_scope:common.Empty)
  })
_sym_db.RegisterMessage(Empty)

QueryInfo = _reflection.GeneratedProtocolMessageType('QueryInfo', (_message.Message,), {

  'WhereEntry' : _reflection.GeneratedProtocolMessageType('WhereEntry', (_message.Message,), {
    'DESCRIPTOR' : _QUERYINFO_WHEREENTRY,
    '__module__' : 'common_pb2'
    # @@protoc_insertion_point(class_scope:common.QueryInfo.WhereEntry)
    })
  ,
  'DESCRIPTOR' : _QUERYINFO,
  '__module__' : 'common_pb2'
  # @@protoc_insertion_point(class_scope:common.QueryInfo)
  })
_sym_db.RegisterMessage(QueryInfo)
_sym_db.RegisterMessage(QueryInfo.WhereEntry)

WhereOperation = _reflection.GeneratedProtocolMessageType('WhereOperation', (_message.Message,), {
  'DESCRIPTOR' : _WHEREOPERATION,
  '__module__' : 'common_pb2'
  # @@protoc_insertion_point(class_scope:common.WhereOperation)
  })
_sym_db.RegisterMessage(WhereOperation)

Operation = _reflection.GeneratedProtocolMessageType('Operation', (_message.Message,), {
  'DESCRIPTOR' : _OPERATION,
  '__module__' : 'common_pb2'
  # @@protoc_insertion_point(class_scope:common.Operation)
  })
_sym_db.RegisterMessage(Operation)

OrderBy = _reflection.GeneratedProtocolMessageType('OrderBy', (_message.Message,), {
  'DESCRIPTOR' : _ORDERBY,
  '__module__' : 'common_pb2'
  # @@protoc_insertion_point(class_scope:common.OrderBy)
  })
_sym_db.RegisterMessage(OrderBy)

Options = _reflection.GeneratedProtocolMessageType('Options', (_message.Message,), {

  'OperationEntry' : _reflection.GeneratedProtocolMessageType('OperationEntry', (_message.Message,), {
    'DESCRIPTOR' : _OPTIONS_OPERATIONENTRY,
    '__module__' : 'common_pb2'
    # @@protoc_insertion_point(class_scope:common.Options.OperationEntry)
    })
  ,
  'DESCRIPTOR' : _OPTIONS,
  '__module__' : 'common_pb2'
  # @@protoc_insertion_point(class_scope:common.Options)
  })
_sym_db.RegisterMessage(Options)
_sym_db.RegisterMessage(Options.OperationEntry)


DESCRIPTOR._options = None
_QUERYINFO_WHEREENTRY._options = None
_OPTIONS_OPERATIONENTRY._options = None
# @@protoc_insertion_point(module_scope)
