image_1 = ['😀',
           '😄',
           '😁',
           '😊',
           '😇',
           '🥰',
           '😍',
           '😋',
           '😚',
           '🤗',
           '💖',
           '💯',
           '👍',
           '🤤',
           '😺',
           '🤞',
           '😀👍',
           '🙍',
           '🙆',
           '🍔',
           '🍕',
           '🍴',
           '🥄',
           '🔪',
           '🌝',
           '⭐',
           '🎉',
           '🏆',
           '🥇',
           '🙋‍♀️🥄',
           '🙆🍴',
           '😀',
           '😄',
           '😁',
           '😊',
           '😇',
           '🥰',
           '😍',
           '😋',
           '😚',
           '🤗',
           '😋👍',
           '😁👍',
           '😋🙋‍♀️']
image_2 = ['🙂',
           '😛',
           '😏',
           '🤣',
           '🤪',
           '🤗',
           '🤤',
           '🤓',
           '🤡',
           '😺',
           '✌',
           '😀☝',
           '😀👏',
           '👩',
           '🙋‍♀️',
           '🐵',
           '🍔',
           '🍕',
           '🍴',
           '🥄',
           '🔪',
           '🌝',
           '⭐',
           '🎉',
           '🙋‍♀️🥄',
           '🤤😀',
           '🤗😛']
image_3 = ['🤔',
           '🤕',
           '🤮',
           '🙁',
           '😭',
           '😖',
           '😩',
           '😤',
           '💢',
           '👎',
           '😑',
           '😩',
           '💩',
           '💥',
           '🤚',
           '🤮😭',
           '🤕💥',
           '😤💢',
           '🤔',
           '🤕',
           '🤮',
           '🙁',
           '😭',
           '😖',
           '😩',
           '😤',
           '💢',
           '👎',
           '😑',
           '😩',
           '💩']
tr_statement_1 = ['fazla kişi yok servis te kötü',
                  'servis kötü ortam da pis',
                  'hiç güzel değildi geliştirmeleri gerek',
                  'yenilcek bi şey yok',
                  'servis aşırı kötü bir saat bekledik gelmedi .siparişi unutmuşlar şaka gibi ya',
                  'çok az hıç doyurmuyor',
                  'Yemekler berbat, sadece mühit iyidi.',
                  'mekan boş olmasına rağmen servis çok yavaştı',
                  'sabah gelmiştim çok ta beklentim vardı ama cidden berbat',
                  'berbat ve çok pahalı',
                  'çok yavaş servis ediyorlar',
                  'çok az asla doyurmuyor',
                  'mühit berbat temizliğinden endişeliyim',
                  'ikinci gelişim çgarson çok kabaydı',
                  'özel menüsü icin gelmiştim görünce şaşırdım çok az',
                  '100TLyi bu kadar şey için ödediğime inanamıyorum',
                  'yemekler memnun edici sadece servis berbat']
tr_statement_2 = ['mekanı zor bulduk ama yemekler çok güzeldi',
                  'Servis çok yavaştı ama tadı iyi.Genel olarak konuşursak, fena değil',
                  'Servis kötü, garsonun tavrı çok soğuk ama yemekler fena değildi',
                  'Sipariş verdikten sonra uzun süre bekledim ama ürünler sorunsuzdu.',
                  'Ortam oldukça rahat ama tadı  sıradan.',
                  'Porsiyon büyük, çevre  sıradandı, iyileştirilmesi gerekiyor.',
                  'yemekler iyide mühit çok kötüydü',
                  'Nasıl desem yemekler büyük bir sorun değil ve servis biraz kayıtsız.',
                  'Yemeklerin tadı fena değildide ama ortam biraz  kötü.',
                  'Lezzetli bir şey yok, sahibi daha yeni yemekler geliştirebilir.',
                  'Yakınlarda işlerim vardı ve buradan geçtim, ortam iyi.',
                  'Üretim herzamanki gibi iyi ama klima çok soğutmuyor',
                  'Çok ucuz, buraya sık sık geliyorum,  daha fazla yeni yemeği olmasını umuyorum.',
                  'Bu mekanı Google\'da buldum  geldim ve çok iyi hissettirdi.',
                  'Yemeklerin tadı ortalama ve miktar çok değil.',
                  'Servis  çok hızlı.',
                  'Bu dükkana sık sık geliyorum ve bugün tadı değişmiş umarım patron buna dikkat eder.',
                  'yazın geldim nerdeyse sıcaktan pişiyordum',
                  'eh yani tamamen acıktığım için bittirdim',
                  'ortam temiz servis yerinde',
                  'Yakınlarda çalışyorum ve buraya birkaç kez geldim',
                  'Öğlen meslektaşımla geldim, fena değildi.',
                  'İşten çıktıktan sonra geldim, birkaç  siparişta bulundum tadın iyileştirilmesi gerekiyor.',
                  'akşam geldim fazla kişi yoktu eh yani']
tr_statement_3 = ['Beni çok etkileyen bir mekan',
                  'çok güzeldi hemen de bittirdim',
                  'gördüğüm gibi beğenmiştim.tadı cidden harika',
                  'çok yemek söyledik.tadı anlatılmaz',
                  'bu mekanı çok beğendim',
                  'on numara beş yıldız',
                  'doğruya doğru gerçekten güzel şeyler var burda. arkadaşlarıma öneririm',
                  'tadı yerinde ve çok sağlıklı .arkadaşlarıma önermeden duramam',
                  'Genel olarak, arkadaşlarla akşam yemeği  ve  sohbet için   çok uygun mekan',
                  'Bu hizmetten çok memnunum.',
                  'bu fiyata bu kaliteyi beklemiyordum beni şaşırttı ve artık sık sık geleceğim.',
                  'bol porsiyonlu ve güzel tadlı  önerilmeli bir mekan',
                  'Tavsiye edilir, tadı gerçekten çok güzel.',
                  'Elüt müzik eşliğinde zarif ortam çok rahat ve umarım hep böyle devam eder',
                  'ortam fena değil.korunma önlemleri de gayet iyi',
                  'Ortam çok iyi, servis de çok düşünceli birde küçük sürprizleri var.',
                  'çalışanlar çok tatlı. çok güzel fotoğraf çekiyor ve bizimle de nasıl açıları yakalamamız gerektiğini öğretiyor',
                  'Garsonlar mağaza hakkında çok derin bir anlayışa sahipler ve ihtiyaçlarımıza göre önerilerde bulunabiliyorlar.Yemekler gerçekten istediğimiz gibiydi',
                  'bugün çok insan olmasına rağmen servis elemanı da yetişiyordu, servis yerindedir, yaklaşımı iyidi ve insanlara çok rahat bir ortam sunuyor',
                  'Garsonlar çok profesyonel,  düzenli ve hızlılar  deneyim harikaydı',
                  'her hafta geldigim mekan artık buranın eskileriyiz',
                  'Fiyat/performans oranı süper yüksek.',
                  'Genel olarak çok iyi bir deneyimdi.',
                  'Arkadaşlarımın oybirliği ile bir dahaki sefer yine burda  partiye geleceğim!',
                  'bol porsiyon takdir edilir',
                  'İlk geldiğimde mağazayı keşfetme fikriyle geldim ve özel bir içecek sipariş ettim.Oldukça keyifli ve övgüye değerdi.',
                  'Yemekler çok zarif, tamamen beklenmedik.',
                  'Bunu platformda bir bakışta yakaladım ve gerçekten çok iyiydi, herkes denemeli.',
                  'çok lezzetliydi hemen bittirdim',
                  'Konumu bulmak çok kolay ve park sorunu yok',
                  'Öğrenci partisi için bir mütiş seçenek bundan sonra sık sık geleceğim.Fiyat da çok uygun',
                  'Ürün çok güzel, tadı hoşuma gitti.',
                  'servis çok düşünceli',
                  'garsonlar güler yüzlü çok cana yakınlar',
                  'Fiyat adil ve deneyim çok iyidi',
                  'mekan temiz ve ferrahtı',
                  'Kapıya park edebilirsiniz ve çok sayıda park yeri var, harika.',
                  'Güzel mekan hem uygun hem bol porsiyon',
                  'konum kolay bulunuyor ve yemekleri de bol koyuyorlar',
                  'İçeri girer girmez, şaşırdım ortam aşırı iyiydi.',
                  'çok memnunum ikinci gelişim',
                  'mühit çok güzel',
                  'Arkadaşlarla akşam yemeği için çok uygun.',
                  'Dekorasyon çok hoşuma gitti ve yemekten sonra birkaç fotoğraf çektim.',
                  'mekanın birçok köşesi fotoğraf çekmek için uygun.',
                  'Genel olarak konuşursak, çok zarif hissettiriyor ve yemekler tamamen beklenmedik bir şekilde yüksek değerde.',
                  'şaşırttıran lezzetler',
                  'güzel mekan ikinci gelisim',
                  'Alışverişten yorulmuştum  buraya geldim, her şey çok iyidi.',
                  'Konumu çok iyi, araba yakındaki otoparka park edilebilir, çok kolay',
                  'fiyat çok uygun daha sık geleceğim',
                  'Bu mekanın porsiyonu oldukça bol.',
                  'Garson çok iyi servis sergiliyor ve bize uygun yemekleri öneriyor.',
                  'Bu mekandan pek umudum yoktu ama denedikten sonra beklentileri aştı.',
                  'Burada defalarca bulundum ve birçok farklı yemek denedim, herkesin denemesini tavsiye ederim.',
                  'önünden geçerken baktım fena değildi deneyim dedim',
                  'Genel tat benim zevkime uygun ve diğer yemekleri denemek için geri geleceğim.',
                  'Mekan geldiğimde garson çok kibardı ve insanlara sıcak bir his veriyor',
                  'Bir arkadaşım tavsiyesi üzere geidim ve bugün denedim gerçekten dediği kadar iyidi.',
                  'Bu mağazayı Disooda gördüm ve bugün denedim gerçekten güzeldi.',
                  'Yani, tavsiyeye değer bir mekan',
                  'indirim gördüm ve geldim  denedim fena değildi.',
                  'dün denedim önerilir',
                  'Bu dükkanı çok beğendim, yemekler beklenmedik bir şekilde iyidi']
tr_word = {'test': ['a', 'b', 'c']}
