image_1 = ['😀',
           '😄',
           '😁',
           '😊',
           '😇',
           '🥰',
           '😍',
           '😋',
           '😚',
           '🤗',
           '💖',
           '💯',
           '👍',
           '🤤',
           '😺',
           '🤞',
           '😀👍',
           '🙍',
           '🙆',
           '🍔',
           '🍕',
           '🍴',
           '🥄',
           '🔪',
           '🌝',
           '⭐',
           '🎉',
           '🏆',
           '🥇',
           '🙋‍♀️🥄',
           '🙆🍴',
           '😀',
           '😄',
           '😁',
           '😊',
           '😇',
           '🥰',
           '😍',
           '😋',
           '😚',
           '🤗',
           '😋👍',
           '😁👍',
           '😋🙋‍♀️']
image_2 = ['🙂',
           '😛',
           '😏',
           '🤣',
           '🤪',
           '🤗',
           '🤤',
           '🤓',
           '🤡',
           '😺',
           '✌',
           '😀☝',
           '😀👏',
           '👩',
           '🙋‍♀️',
           '🐵',
           '🍔',
           '🍕',
           '🍴',
           '🥄',
           '🔪',
           '🌝',
           '⭐',
           '🎉',
           '🙋‍♀️🥄',
           '🤤😀',
           '🤗😛']
image_3 = ['🤔',
           '🤕',
           '🤮',
           '🙁',
           '😭',
           '😖',
           '😩',
           '😤',
           '💢',
           '👎',
           '😑',
           '😩',
           '💩',
           '💥',
           '🤚',
           '🤮😭',
           '🤕💥',
           '😤💢',
           '🤔',
           '🤕',
           '🤮',
           '🙁',
           '😭',
           '😖',
           '😩',
           '😤',
           '💢',
           '👎',
           '😑',
           '😩',
           '💩']
tr_statement_1 = ['fazla kişi yok servis te kötü',
                  'servis kötü ortam da pis',
                  'hiç güzel değildi geliştirmeleri gerek',
                  'yenilcek bi şey yok',
                  'servis aşırı kötü bir saat bekledik gelmedi .siparişi unutmuşlar şaka gibi ya',
                  'çok az hıç doyurmuyor',
                  'Yemekler berbat, sadece mühit iyidi.',
                  'mekan boş olmasına rağmen servis çok yavaştı',
                  'sabah gelmiştim çok ta beklentim vardı ama cidden berbat',
                  'berbat ve çok pahalı',
                  'çok yavaş servis ediyorlar',
                  'çok az asla doyurmuyor',
                  'mühit berbat temizliğinden endişeliyim',
                  'ikinci gelişim çgarson çok kabaydı',
                  'özel menüsü icin gelmiştim görünce şaşırdım çok az',
                  '100TLyi bu kadar şey için ödediğime inanamıyorum',
                  'yemekler memnun edici sadece servis berbat']
tr_statement_2 = ['mekanı zor bulduk ama yemekler çok güzeldi',
                  'Servis çok yavaştı ama tadı iyi.Genel olarak konuşursak, fena değil',
                  'Servis kötü, garsonun tavrı çok soğuk ama yemekler fena değildi',
                  'Sipariş verdikten sonra uzun süre bekledim ama ürünler sorunsuzdu.',
                  'Ortam oldukça rahat ama tadı  sıradan.',
                  'Porsiyon büyük, çevre  sıradandı, iyileştirilmesi gerekiyor.',
                  'yemekler iyide mühit çok kötüydü',
                  'Nasıl desem yemekler büyük bir sorun değil ve servis biraz kayıtsız.',
                  'Yemeklerin tadı fena değildide ama ortam biraz  kötü.',
                  'Lezzetli bir şey yok, sahibi daha yeni yemekler geliştirebilir.',
                  'Yakınlarda işlerim vardı ve buradan geçtim, ortam iyi.',
                  'Üretim herzamanki gibi iyi ama klima çok soğutmuyor',
                  'Çok ucuz, buraya sık sık geliyorum,  daha fazla yeni yemeği olmasını umuyorum.',
                  'Bu mekanı Google\'da buldum  geldim ve çok iyi hissettirdi.',
                  'Yemeklerin tadı ortalama ve miktar çok değil.',
                  'Servis  çok hızlı.',
                  'Bu dükkana sık sık geliyorum ve bugün tadı değişmiş umarım patron buna dikkat eder.',
                  'yazın geldim nerdeyse sıcaktan pişiyordum',
                  'eh yani tamamen acıktığım için bittirdim',
                  'ortam temiz servis yerinde',
                  'Yakınlarda çalışyorum ve buraya birkaç kez geldim',
                  'Öğlen meslektaşımla geldim, fena değildi.',
                  'İşten çıktıktan sonra geldim, birkaç  siparişta bulundum tadın iyileştirilmesi gerekiyor.',
                  'akşam geldim fazla kişi yoktu eh yani']
tr_statement_3 = ['Beni çok etkileyen bir mekan',
                  'çok güzeldi hemen de bittirdim',
                  'gördüğüm gibi beğenmiştim.tadı cidden harika',
                  'çok yemek söyledik.tadı anlatılmaz',
                  'bu mekanı çok beğendim',
                  'on numara beş yıldız',
                  'doğruya doğru gerçekten güzel şeyler var burda. arkadaşlarıma öneririm',
                  'tadı yerinde ve çok sağlıklı .arkadaşlarıma önermeden duramam',
                  'Genel olarak, arkadaşlarla akşam yemeği  ve  sohbet için   çok uygun mekan',
                  'Bu hizmetten çok memnunum.',
                  'bu fiyata bu kaliteyi beklemiyordum beni şaşırttı ve artık sık sık geleceğim.',
                  'bol porsiyonlu ve güzel tadlı  önerilmeli bir mekan',
                  'Tavsiye edilir, tadı gerçekten çok güzel.',
                  'Elüt müzik eşliğinde zarif ortam çok rahat ve umarım hep böyle devam eder',
                  'ortam fena değil.korunma önlemleri de gayet iyi',
                  'Ortam çok iyi, servis de çok düşünceli birde küçük sürprizleri var.',
                  'çalışanlar çok tatlı. çok güzel fotoğraf çekiyor ve bizimle de nasıl açıları yakalamamız gerektiğini öğretiyor',
                  'Garsonlar mağaza hakkında çok derin bir anlayışa sahipler ve ihtiyaçlarımıza göre önerilerde bulunabiliyorlar.Yemekler gerçekten istediğimiz gibiydi',
                  'bugün çok insan olmasına rağmen servis elemanı da yetişiyordu, servis yerindedir, yaklaşımı iyidi ve insanlara çok rahat bir ortam sunuyor',
                  'Garsonlar çok profesyonel,  düzenli ve hızlılar  deneyim harikaydı',
                  'her hafta geldigim mekan artık buranın eskileriyiz',
                  'Fiyat/performans oranı süper yüksek.',
                  'Genel olarak çok iyi bir deneyimdi.',
                  'Arkadaşlarımın oybirliği ile bir dahaki sefer yine burda  partiye geleceğim!',
                  'bol porsiyon takdir edilir',
                  'İlk geldiğimde mağazayı keşfetme fikriyle geldim ve özel bir içecek sipariş ettim.Oldukça keyifli ve övgüye değerdi.',
                  'Yemekler çok zarif, tamamen beklenmedik.',
                  'Bunu platformda bir bakışta yakaladım ve gerçekten çok iyiydi, herkes denemeli.',
                  'çok lezzetliydi hemen bittirdim',
                  'Konumu bulmak çok kolay ve park sorunu yok',
                  'Öğrenci partisi için bir mütiş seçenek bundan sonra sık sık geleceğim.Fiyat da çok uygun',
                  'Ürün çok güzel, tadı hoşuma gitti.',
                  'servis çok düşünceli',
                  'garsonlar güler yüzlü çok cana yakınlar',
                  'Fiyat adil ve deneyim çok iyidi',
                  'mekan temiz ve ferrahtı',
                  'Kapıya park edebilirsiniz ve çok sayıda park yeri var, harika.',
                  'Güzel mekan hem uygun hem bol porsiyon',
                  'konum kolay bulunuyor ve yemekleri de bol koyuyorlar',
                  'İçeri girer girmez, şaşırdım ortam aşırı iyiydi.',
                  'çok memnunum ikinci gelişim',
                  'mühit çok güzel',
                  'Arkadaşlarla akşam yemeği için çok uygun.',
                  'Dekorasyon çok hoşuma gitti ve yemekten sonra birkaç fotoğraf çektim.',
                  'mekanın birçok köşesi fotoğraf çekmek için uygun.',
                  'Genel olarak konuşursak, çok zarif hissettiriyor ve yemekler tamamen beklenmedik bir şekilde yüksek değerde.',
                  'şaşırttıran lezzetler',
                  'güzel mekan ikinci gelisim',
                  'Alışverişten yorulmuştum  buraya geldim, her şey çok iyidi.',
                  'Konumu çok iyi, araba yakındaki otoparka park edilebilir, çok kolay',
                  'fiyat çok uygun daha sık geleceğim',
                  'Bu mekanın porsiyonu oldukça bol.',
                  'Garson çok iyi servis sergiliyor ve bize uygun yemekleri öneriyor.',
                  'Bu mekandan pek umudum yoktu ama denedikten sonra beklentileri aştı.',
                  'Burada defalarca bulundum ve birçok farklı yemek denedim, herkesin denemesini tavsiye ederim.',
                  'önünden geçerken baktım fena değildi deneyim dedim',
                  'Genel tat benim zevkime uygun ve diğer yemekleri denemek için geri geleceğim.',
                  'Mekan geldiğimde garson çok kibardı ve insanlara sıcak bir his veriyor',
                  'Bir arkadaşım tavsiyesi üzere geidim ve bugün denedim gerçekten dediği kadar iyidi.',
                  'Bu mağazayı Disooda gördüm ve bugün denedim gerçekten güzeldi.',
                  'Yani, tavsiyeye değer bir mekan',
                  'indirim gördüm ve geldim  denedim fena değildi.',
                  'dün denedim önerilir',
                  'Bu dükkanı çok beğendim, yemekler beklenmedik bir şekilde iyidi']
tr_word_statistical = ['güzel',
                       'lezzetli',
                       'yemek',
                       'mekan',
                       'tavsiye',
                       'servis',
                       'olarak',
                       'harika',
                       'yemekler',
                       'hizmet',
                       'mükemmel',
                       'lezzet',
                       'gayet',
                       'kebap',
                       'sonra',
                       'gerçekten',
                       'uygun',
                       'yemeği',
                       'restoran',
                       'kesinlikle',
                       'yemekleri',
                       'akşam',
                       'oldukça',
                       'mutlaka',
                       'zaman',
                       'Yemekler',
                       'balık',
                       'ilgili',
                       'hızlı',
                       'Servis',
                       'taze',
                       'ancak',
                       'tercih',
                       'fiyatlar',
                       'geldi',
                       'Fiyatlar',
                       'temiz',
                       'göre',
                       'güzeldi',
                       'Adana',
                       'bir yer',
                       'bir mekan',
                       'tavsiye ederim',
                       'çok güzel',
                       'güzel bir',
                       'çok iyi',
                       'en iyi',
                       'çok lezzetli',
                       'this restaurant',
                       'in Istanbul',
                       'harika bir',
                       'güler yüzlü',
                       've çok',
                       've lezzetli',
                       'lezzetli ve',
                       'akşam yemeği',
                       'yemeği için',
                       'yemek için',
                       'bir restoran',
                       'akşam yemeği için',
                       'çok güzel bir',
                       'bir akşam yemeği',
                       'güzel bir mekan',
                       'güzel bir yer',
                       'herkese tavsiye ederim',
                       'çok cana yakın',
                       'çok lezzetli ve',
                       'kesinlikle tavsiye ederim',
                       'cana yakın ve',
                       'çok memnun kaldık',
                       've güler yüzlü',
                       'güler yüzlü ve',
                       'harika bir yer',
                       'çok güzel ve',
                       'öğle yemeği için',
                       'gereken bir yer',
                       'için harika bir',
                       'çok iyi bir',
                       've güzel bir',
                       'dost canlısı ve',
                       'çok iyi ve',
                       'Çok güzel bir',
                       'in questo ristorante',
                       'taze ve lezzetli',
                       'şiddetle tavsiye ederim',
                       'Kesinlikle tavsiye ederim',
                       'çok dost canlısı',
                       've cana yakın',
                       'z']
tr_word = {'güzel': ['hoş', 'kibar', 'biçimli', 'sevimli'],
           'lezzetli': ['nefis', 'hoş', 'zevkli', 'tadı güzel', 'harika'],
           'yemek': ['tüketmek', 'çok yemek yemek'],
           'mekan': ['uzay'],
           'tavsiye': ['danışma', 'nasihat', 'öğüt', 'uyarı', 'fikir'],
           'servis': ['hizmet', 'görev', 'faaliyet', 'askerlik'],
           'olarak': ['kadar', 'iken'],
           'harika': ['şahane', 'şaşılacak', 'harikulâde'],
           'hizmet': ['servis', 'görev', 'ayin', 'faaliyet', 'askerlik'],
           'mükemmel': ['kusursuz', 'üstün', 'nefis', 'seçkin'],
           'lezzet': ['tat', 'çeşni', 'tad', 'koku', 'hava'],
           'gayet': ['gerçekten', 'aslında', 'cidden', 'sahiden', 'kesinlikle'],
           'sonra': ['ardından', 'arkasından'],
           'gerçekten': ['aslında', 'cidden', 'sahiden', 'kesinlikle'],
           'uygun': ['yerinde', 'özgü', 'has', 'biçilmiş kaftan'],
           'restoran': ['lokanta'],
           'kesinlikle': ['kesin olarak', 'kuşkusuz', 'elbette', 'tamamen', 'açıkça'],
           'akşam': ['son bölüm', 'son evreler'],
           'oldukça': ['tamamen', 'pek', 'tam olarak', 'bayağı'],
           'mutlaka': ['zorunlu', 'mutlâka'],
           'zaman': ['vakit', 'kere', 'uygun zaman'],
           'ilgili': ['hakkında', 'konusunda', 'dair', 'etrafında', 'üstünde'],
           'hızlı': ['hızla', 'çabuk', 'süratli', 'seri'],
           'Servis': ['hizmet', 'görev', 'ayin'],
           'taze': ['temiz', 'canlı', 'serin', 'zinde'],
           'ancak': ['ama', 'fakat'],
           'tercih': ['öncelik', 'tercih hakkı', 'yeğleme'],
           'temiz': ['saf', 'lekesiz'],
           'göre': ['tarafından', 'ile', 'yoluyla'],
           'bir mekan': ['bir uzay', 'bir alan', 'bir boşluk', 'bir mekân'],
           'tavsiye ederim': ['Ben tavsiye ediyorum'],
           'çok güzel': ['çok hoş', 'çok güzel'],
           'çok iyi': ['çok iyi'],
           'en iyi': ['tepe'],
           'çok lezzetli': ['çok lezzetli'],
           'harika bir': ['harika'],
           'güler yüzlü': ['uysal', 'tebessüm eden'],
           've lezzetli': ['ve nefis', 've hoş'],
           'lezzetli ve': ['nefis ve', 'hoş ve'],
           'akşam yemeği': ['hafif akşam yemeği', 'yemek', 'ziyafet'],
           'yemeği için': ['akşam yemeği için'],
           'bir restoran': ['bir lokanta'],
           'akşam yemeği için': ['öğlen yemeği için'],
           'çok güzel bir': ['çok güzel biri'],
           'bir akşam yemeği': ['öğle yemeği'],
           'güzel bir mekan': ['güzel bir mekan'],
           'güzel bir yer': ['güzel yer'],
           'herkese tavsiye ederim': ['öneririm'],
           'çok cana yakın': ['çok cana yakın'],
           'çok lezzetli ve': ['çok nefis ve', 'çok harika ve'],
           'kesinlikle tavsiye ederim': ['Ben tavsiye ederim'],
           'cana yakın ve': ['arkadaşça ve', '"ulaşılabilir'],
           'çok memnun kaldık': ['biz çok memnunuz', 'Çok memnun olduk'],
           've güler yüzlü': ['ve gülümseyerek', 've gülen'],
           'güler yüzlü ve': ['gülümseyerek ve', 'komik ve'],
           'harika bir yer': ['harika yer'],
           'çok güzel ve': ['çok hoş ve', 'çok sevimli ve'],
           'öğle yemeği için': ['akşam yemeği için'],
           'gereken bir yer': ['olmak için bir yer'],
           'için harika bir': ['için harika bir'],
           'çok iyi bir': ['çok güzel bir', 'çok hoş bir', 'çok şirin bir', 'çok kurnaz bir'],
           've güzel bir': ['ve güzel bir'],
           'dost canlısı ve': ['arkadaşça ve', 'arkadaş canlısı ve'],
           'çok iyi ve': ['çok güzel ve', 'çok kibar ve', 'çok nefis ve'],
           'Çok güzel bir': ['çok güzel', 'çok kibar ve', 'çok nefis ve'],
           'taze ve lezzetli': ['temiz ve zevkli'],
           'şiddetle tavsiye ederim': ['herkese tavsiye ederim', 'Kesinlikle tavsiye ederim'],
           'Kesinlikle tavsiye ederim': ['şiddetle tavsiye ederim', 'herkese tavsiye ederim'],
           'çok dost canlısı': ['çok arkadaşça', 've ulaşılabilir'],
           've cana yakın': ['ve ulaşılabilir', 'çok arkadaşça'],
           'özellikle': ['bilhassa'],
           'yakın': ['sıkı', 'kapalı', 'bitişik'],
           'bile': ['olsa bile'],
           'sadece': ['bir tek', 'sırf'],
           'kaliteli': ['nitelikli', 'yetkili'],
           'memnun': ['hoşnut', 'tatmin olmuş'],
           'sıcak': ['ateşli', 'seksi'],
           'fazla': ['çok', 'hayli'],
           'ortam': ['çevre', 'etraf'],
           'burada': ['buraya', 'burda'],
           'mezeler': ['meze', 'iştah açıcılar'],
           'fiyat': ['bedel', 'bedel', 'değer', 'para ödülü'],
           'makul': ['mantıklı', 'akılcı'],
           'muhteşem': ['olağanüstü', 'göz alıcı', 'şaşırtıcı'],
           'başarılı': ['mükemmel'],
           'pahalı': ['masraflı', 'pahalıya mal olan', 'pahalı'],
           'aynı': ['benzer'],
           'yüzlü': ['kaplı'],
           'biri': ['bir tane', 'birisi'],
           'guzel': ['güzel', 'hoş', 'dakik'],
           'kötü': ['fena', 'bozuk'],
           'küçük': ['az', 'ufak'],
           'oldu': ['Peki!'],
           'lezzetliydi': ['bu lezzetliydi'],
           'Mekan': ['uzay', 'alan', 'yüzölçümü'],
           'rağmen': ['karşın'],
           'büyük': ['mükemmel', 'önemli'],
           'icin': ['amacıyla', 'göre'],
           'tekrar': ['yeniden', 'yine', 'bir daha'],
           'ziyaret': ['vizite', 'misafirlik'],
           'fakat': ['ama', 'ancak'],
           'meze': ['iştah açıcı'],
           'keyifli': ['eğlenceli'],
           'tadı': ['damak zevki'],
           'olması': ['Sahip olmak'],
           'kalitesi': ['kalitesi'],
           'comida': ['komedide'],
           'farklı': ['değişik', 'çeşitli'],
           'sipariş': ['düzen', 'emir', 'kişi'],
           'kişi': ['düzen', 'emir', 'sipariş'],
           'manzara': ['görünüm', 'bakış', 'görüş'],
           'deniz': ['denizle ilgili'],
           'içinde': ['zarfında'],
           'Kesinlikle': ['Aynen!'],
           'Harika': ['Çok iyi'],
           'Özellikle': ['bilhassa'],
           'manzarası': ['görüş'],
           'başka': ['farklı'],
           'özel': ['has', 'özellikli'],
           'yanında': ['dışında', 'nazaran'],
           'para': ['nakit'],
           'diğer': ['öteki'],
           'güleryüzlü': ['gülümseyen', 'güler yüzlü'],
           'olsun': ['Çok kötü'],
           'ilgi': ['faiz', 'çıkar'],
           'teşekkür': ['şükür'],
           'menü': ['mönü', 'yemek listesi'],
           'hemen': ['şimdi', 'şu anda'],
           }


shop_ids = []