[package]
name = "k8_view"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ssh2="0.9.1"
anyhow="1.0.44"