[package]
name = "color"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# tokio = { version = "1.10.0", features = ["full"] }
regex = "1.5.4"
# colored = "2.0.0"